# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 952cad4868d9a812db213e3f67ad2a91791563ab97ce460f8c5f07052b862a16b06156ab4bea3e8f48fb1a14bfd3db33c38d5c42bb264d592627059b33d6557e

test:
  secret_key_base: 66a8c9d117cf468fa1b59529b92ed7a821d587becd769560c675a952ecc1a3499093a60fb64fbe830442a969b30611d3d980a3a033f278042fc94bf19634bcfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
